"""
Generated by 'django-admin startproject' using Django 1.8.7.
"""

import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

STATIC_ROOT= '/home/user/static/'
MEDIA_ROOT= '/home/user/media/'

STATICFILES_DIRS = [
    "../home/topadmin/top/static/",
]

SECRET_KEY = 'smr3$-4))eojf2h48w@n6k0jlly!w0wktsu3s)gl3shs+wy=%w'

DEBUG = True

import sys
sys.path.append("../home/topadmin/") 

INSTALLED_APPS = (
	'client_custom',
	# 'reversion',
	'django.contrib.admin',
	'django.contrib.auth',
	'django.contrib.contenttypes',
	'django.contrib.sessions',
	'django.contrib.messages',
	'django.contrib.staticfiles',
	'django.contrib.humanize',
	'top.mobileapp',
	'top.agency',
	'top.main',
	'top.pax',
	'top.accounting',
	'top.pricelists',
	'top.suppliers',
	'top.planning',
	'top.reservations',
	'top.vouchers',
	'top.agents',
	'top.lists',
	'top.others',
	'top.reports',
	'top.accreports',
	'top.controllerreports',
	'top.passwords',
	'top.transpop',
	'top.trac',
	'top.innstant'
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'top.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['/home/topadmin/top/templates/', '/home/user/client_custom/templates/'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'clienttop.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
		'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
		# 'ENGINE': 'django.db.backends.postgresql_psycopg2',
		# 'NAME':'topdb', 'USER':'', 'PASSWORD': '', 'HOST': 'localhost', 'PORT': '',
    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Jerusalem'
USE_I18N = True
USE_L10N = False
USE_TZ = True

DATE_FORMAT = 'd M y'
SHORT_DATE_FORMAT = 'd.m.Y'
DATE_INPUT_FORMATS = ('%d/%m/%y', '%d/%m/%Y', '%Y-%m-%d')

SHORT_TIME_FORMAT = 'G:i'
TIME_FORMAT = 'H:i'

SHORT_DATETIME_FORMAT = 'd.m.y G:i'



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'
MEDIA_URL = '/media/'
BASE_URL = ''

LOGIN_REDIRECT_URL = '/'
LOGIN_URL = '/login/'
AUTH_PROFILE_MODULE = 'agency.employee'
#AUTH_USER_MODEL = 'agency.employee'

FILES_START = "30000"

ALLOWED_HOSTS = ['*']

